# Generated by Django 5.1.4 on 2026-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Project', max_length=255)),
                ('current_step', models.PositiveIntegerField(default=2)),
                ('schema_ok', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
