# Generated by Django 5.1.4 on 2026-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='missing_strategy',
            field=models.CharField(default='median', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='normalization_method',
            field=models.CharField(default='zscore', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='smote_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='train_ratio',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
